Вывод будет следующим:
error
так как "err" в "main()" является экземпляром интерфейса "error", и ему присваивается указатель на nil-значение типа "*customError" из "test()". Тип "customError" запоминается в "err", что уже делает его не-nil-овым интерфейсом.